
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
COMMENT ON SCHEMA "public" IS 'standard public schema';
CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
SET default_tablespace = '';
SET default_table_access_method = "heap";
CREATE TABLE IF NOT EXISTS "public"."descriptionstopword" (
    "id" bigint NOT NULL,
    "word" character varying NOT NULL
);
ALTER TABLE "public"."descriptionstopword" OWNER TO "postgres";
ALTER TABLE "public"."descriptionstopword" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DescriptionStopWord_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."titlestopword" (
    "id" bigint NOT NULL,
    "word" character varying NOT NULL
);
ALTER TABLE "public"."titlestopword" OWNER TO "postgres";
ALTER TABLE "public"."titlestopword" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TitleStopWord_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL
);
ALTER TABLE "public"."categories" OWNER TO "postgres";
ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS "public"."vacancies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "v_id" bigint NOT NULL,
    "link" character varying DEFAULT ''::character varying,
    "date" character varying DEFAULT ''::character varying,
    "title" character varying DEFAULT ''::character varying,
    "company" character varying DEFAULT ''::character varying,
    "cities" character varying DEFAULT ''::character varying,
    "description" character varying DEFAULT ''::character varying,
    "status" character varying DEFAULT 'new'::character varying NOT NULL,
    "read" boolean DEFAULT false NOT NULL,
    "category_id" bigint,
    "salary" character varying DEFAULT ''::character varying
);
ALTER TABLE "public"."vacancies" OWNER TO "postgres";
ALTER TABLE "public"."vacancies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."vacancies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY "public"."descriptionstopword"
    ADD CONSTRAINT "DescriptionStopWord_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."titlestopword"
    ADD CONSTRAINT "TitleStopWord_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "category_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."descriptionstopword"
    ADD CONSTRAINT "descriptionstopword_word_key" UNIQUE ("word");
ALTER TABLE ONLY "public"."titlestopword"
    ADD CONSTRAINT "titlestopword_word_key" UNIQUE ("word");
ALTER TABLE ONLY "public"."vacancies"
    ADD CONSTRAINT "vacancies_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."vacancies"
    ADD CONSTRAINT "vacancies_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id");
CREATE POLICY "ALL" ON "public"."descriptionstopword" TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "ALL" ON "public"."titlestopword" TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "ALL" ON "public"."vacancies" TO "authenticated" USING (true) WITH CHECK (true);
CREATE POLICY "Select" ON "public"."categories" FOR SELECT TO "authenticated" USING (true);
ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."descriptionstopword" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."titlestopword" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."vacancies" ENABLE ROW LEVEL SECURITY;
ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."descriptionstopword" TO "anon";
GRANT ALL ON TABLE "public"."descriptionstopword" TO "authenticated";
GRANT ALL ON TABLE "public"."descriptionstopword" TO "service_role";
GRANT ALL ON SEQUENCE "public"."DescriptionStopWord_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DescriptionStopWord_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DescriptionStopWord_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."titlestopword" TO "anon";
GRANT ALL ON TABLE "public"."titlestopword" TO "authenticated";
GRANT ALL ON TABLE "public"."titlestopword" TO "service_role";
GRANT ALL ON SEQUENCE "public"."TitleStopWord_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TitleStopWord_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TitleStopWord_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "service_role";
GRANT ALL ON TABLE "public"."vacancies" TO "anon";
GRANT ALL ON TABLE "public"."vacancies" TO "authenticated";
GRANT ALL ON TABLE "public"."vacancies" TO "service_role";
GRANT ALL ON SEQUENCE "public"."vacancies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."vacancies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."vacancies_id_seq" TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
drop extension if exists "pg_net";
-- CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();
-- CREATE TRIGGER protect_buckets_delete BEFORE DELETE ON storage.buckets FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();
-- CREATE TRIGGER protect_objects_delete BEFORE DELETE ON storage.objects FOR EACH STATEMENT EXECUTE FUNCTION storage.protect_delete();
-- CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();
